# Generated by Django 3.2.12 on 2023-04-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='issue_a',
            new_name='BLUE TEAM',
        ),
        migrations.AddField(
            model_name='question',
            name='RED TEAM',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
